### PR TITLE
Throw an exception if the provider returns more results than it should

### LINKED ISSUE #4: Throw an exception if the provider returns more results than expected
As observed by @rmccue, if the media library attachments query returns _more_ results than expected then it breaks the pagination.

AMF should throw an exception if the provider returns more than the requested `posts_per_page` number of media items.

### PR DESCRIPTION
**Pull request by johnbillion**
Fixes #4.

This makes two changes:

1. Returns an HTTP 500 response when there's a problem with the response from the provider so it's more visible to developers while we wait for #22 .
2. Throws an exception (which is caught in `ajax_query_attachments()` and converted to a JSON error) if the provider returns too many results.

### CODE REVIEW

File: inc/Provider.php [hunk 1]
```diff
@@ -78,6 +78,7 @@ public function supports_filter_user() : bool {
 	 * Fetches a list of media items that are ultimately used directly by the media managaer.
 	 *
 	 * @param array $args Raw query arguments from the POST request in the media manager.
+	 * @throws Exception Thrown if an unrecoverable error occurs.
```
Comment (tfrommen) [inline inc/Provider.php:81]: I think the description can be a bit improved. Something like this, maybe?

```suggestion
	 * @throws Exception Thrown if the provider returns too many media items.
```

File: inc/Provider.php [hunk 2]
```diff
@@ -130,6 +131,16 @@ final public function request_items( array $args ) : MediaList {
 			return $items;
 		}
 
+		if ( isset( $args['posts_per_page'] ) && ( $args['posts_per_page'] > 0 ) && count( $array ) > $args['posts_per_page'] ) {
+			throw new Exception(
```
Comment (tfrommen) [inline inc/Provider.php:135]: How about using `RangeException` instead? (This would require a namespace import at the top of the file.)
